- name: Upload files to Nexus
  hosts: localhost
  gather_facts: false
  vars:
    nexus_url: "http://localhost:8081/repository/repositories"
    nexus_username: "admin"
    nexus_password: "68ca3a1a-2a76-409e-b9a7-7c6b9adcf329"
    repository_name: "reports"
    source_directory: "/home/ganesh/sample"
    target_directory: "report"

  tasks:
    - name: Get file list
      find:
        paths: "{{ source_directory }}"
        file_type: any
        recurse: yes
      register: files_to_upload

    - name: Upload files to Nexus
      uri:
        url: "{{ nexus_url }}/repository/{{ repository_name }}/{{ target_directory }}/{{ item.path | regex_replace('^' + source_directory, '') }}"
        method: PUT
        user: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        src: "{{ item.path }}"
        force_basic_auth: yes
        status_code: 401
      loop: "{{ files_to_upload.files }}"

