- hosts: localhost
  #become: yes
  gather_facts: yes

  vars:

    #random settings
    csv_path: /tmp
    csv_filename: adapter-data.csv
    headers: More_Than2Interfaces, adapter, adpater_state, DNS-Servers, ip_address, subnetMask, gateway, mac_address, dhcp_status

  tasks:

    - name: get facts
      setup:
      register: facts

        #- name: Get first adapter status
        #shell:
        #cmd: ip link show
        #register: first_adapter_status
    - name: run tasks for each interface
      include_tasks: "TaskAdapter1.yml"
      with_items: "{{ ansible_interfaces }}"
      run_once: false
   
    - name: Save CSV headers
      ansible.builtin.lineinfile:
        dest: "{{ csv_path }}/{{ csv_filename }}"
        line: "{{ headers }}"
        create: true
        state: present
      delegate_to: localhost
      run_once: true
    #with_items: "{{ ansible_interfaces }}"

    - name: Build out CSV file
      ansible.builtin.lineinfile:
        dest: "{{ csv_path}}/{{ csv_filename }}"
        line: "{{morethan_two_interfaces}},{{ adapter }},{{adapter_state.stdout}},{{dns_servers}},{{ip_address}},{{subnetMask}},{{gateway}},{{mac_address}},{{dhcp_status.stdout}}"
        create: true
        state: present
      delegate_to: localhost

    - name: Read in CSV to variable
      community.general.read_csv:
        path: "{{ csv_path}}/{{ csv_filename }}"
      register: csv_file
      delegate_to: localhost
      run_once: true
      #with_item: "{{ ansible_interfaces}}"
