- name: Get Adapter Name
  set_fact:
    adapter: "{{ item }}"

- name: adapter_state
  shell:
    cmd: nmcli device status | grep "{{ item }}" | awk '{print $3}'
  register: adapter_state

- name: Get DHCP status
  shell:
    cmd: systemctl status dhcpd | grep Active | awk '{print $2}'
  register: dhcp_status

- name: Get Interface length
  set_fact:
    interface_total: "{{ ansible_facts.interfaces | length }}"

- name: Check if more than two interfaces
  set_fact:
    morethan_two_interfaces: "True"
  when: interface_total > "2"

- name: check if less than or equal to 2
  set_fact:
    morethan_two_interfaces: "False"
  when: interface_total <= "2"

- name: set facts for the variables
  set_fact:

    dns_servers: "{{ ansible_dns.nameservers }}"
    ip_address: "{{ ansible_default_ipv4.address }}"
    subnetMask: "{{ (ansible_default_ipv4.network + '/' + ansible_default_ipv4.netmask) | ipaddr('network/prefix') }}"
    gateway: "{{ ansible_default_ipv4.gateway }}"
    mac_address: "{{ ansible_default_ipv4.macaddress }}"
