- name: Check whether a package called {{ package }} is installed
  shell:
    cmd: rpm -qa | grep {{ package }}
  register: available_packages

- name: show installed {{package}}
  debug:
    msg: "{{available_packages.stdout}}"
