---
# tasks file for suse-package-manager
#- name: package collection
 # package_facts:
  #  manager: auto

- name: Install {{ package }}
  include_tasks: install.yml
  when: 
    - role_function == "install"

- name: uninstall {{ package }}
  include_tasks: remove.yml
  when: 
    - role_function == "remove"

- name: check {{ package }}
  include_tasks: check.yml
  when: 
    - role_function == "check"
